CATEGORIES_1 = """1, SLEEPING, ARISING, AND WASHING : The chapter provides guidelines for proper conduct, prayer, and hygiene in the morning. It advises against excessive sleep and lying down in the east-west direction. One should express sadness about the destruction of the Temple in prayers during specific periods of the night. Upon waking, a person should be mindful of God's presence, promptly prepare to serve God, dress appropriately, and wash their hands, reciting a blessing. Proper hygiene and modest behavior in the toilet are also emphasized.
2,  FRINGES (TZITZIS) : This chapter provides detailed guidelines for the use and requirements of "tzitzit," the fringes attached to a garment with four or more corners. Tzitzit are required on garments primarily used to cover the body, owned by Jews, and worn during the day or at night if they are typically worn during the day. The tzitzit must be made of material permitted for religious use, spun and twisted by a Jew, and knotted in a specific manner with at least four inches of winding and double-knotted ends.
3,  TEFILLIN (PHYLACTERIES) : The chapter provides detailed instructions on Tefillin, leather boxes containing Torah passages that are worn on the hand and arm. The Tefillin must be made from the skin of a kosher animal or bird, and the passages written on parchment by a literate, religious adult male Jew with proper intent and attention to specific rules. The boxes are square, with the head Tefillin having four compartments and an embossed letter "shin," while the arm Tefillin has one compartment and a knot in the shape of the letter "yud."
4,  MORNING PRAYERS (shacharis) : The chapter outlines various aspects of morning prayers and the requirements for reciting blessings throughout the day. It emphasizes the importance of reciting blessings before engaging in Torah-related activities and the significance of reading specific passages from the Torah and Psalms during the morning prayers. It also provides guidelines for selecting an appropriate leader for the prayer service and the conditions for reciting certain prayers in the presence of ten adult male Jews. 
5,  SHEMA : The chapter discusses the recitation of the Shema, emphasizing the need for great concentration and intent, particularly in the first verse. It provides guidelines for reciting blessings before and after the Shema, and the appropriate intentions at specific parts of the prayer. There are also instructions on when and how to recite the Shema, along with exceptions and prohibitions in specific situations.
6,  SHEMONEH ESREH (davening): The chapter provides detailed guidelines for the recitation of the Shemoneh Esreh, a prayer comprising 18 blessings. It explains when private prayers can be inserted and when modifications are made for special occasions throughout the year. The role of the prayer leader in repeating the Shemoneh Esreh after the congregation, as well as rules for shorter versions of the prayer in specific situations, are also outlined. Additionally, it advises on the proper timing and preparation for reciting the morning Shemoneh Esreh prayer.
7,  THE PRIESTLY BLESSING AND THE CONCLUSION OF THE MORNING PRAYERS : During the Shemoneh Esreh prayer, when the leader reaches the third-from-last blessing, the Kohanim present go up to the platform (duchan) and recite the priestly blessing facing the Ark. The congregation should concentrate on receiving the blessing, looking downward during its recitation. Certain conditions prevent a Kohen from reciting the blessing, and the priestly blessing is now typically recited only on holidays during the Musaf service. After the prayer, the congregation sits and recites Tachanun, a supplication, followed by additional prayers on Mondays and Thursdays, Psalms 145 and 20, U-Va Le-Tzion, Aleinu, and the mourner's Kaddish.
8,  THE TORAH READING : On Mondays, Thursdays, and Sabbath afternoons, the Torah is read in three parts, with a Kohen, Levite, and Israelite taking turns. The reading must be at least nine or ten consecutive verses long, and each reader must read at least three verses. The congregation should stand, listen attentively, and not engage in unrelated activities during the reading. After the reading is finished, the Torah scroll is shown to the congregation, who recite a blessing, and then the scroll is rolled up and covered before proceeding with other readings.
9,  THE SYNAGOGUE (shul): A synagogue should be built with specific considerations such as its location, size, and layout. Proper conduct is required inside the synagogue and house of study, including not using them for non-religious purposes, maintaining cleanliness, and showing respect. Holy things, including Torah scrolls, must be treated with care and not used for disrespectful purposes, and surplus funds collected for holy purposes can be repurposed for other sacred endeavors. Torah study is highly valued and should be prioritized before other daily activities.
10, WASHING BEFORE EATING (netilas yadayim) : The chapter advises having a substantial meal by the end of the first third of the day or no later than noon. Hand washing is required before eating bread, baked grain food, or food washed in liquid. The washing can be done by pouring water from a utensil or immersing hands entirely. There should be no interruption between washing and eating.
11, EATING A MEAL : This chapter discusses the procedure for starting a meal with bread, including grasping the bread with both hands, reciting the appropriate blessing, and the host distributing the bread to others. When eating together, proper etiquette is emphasized, such as not talking while eating and showing politeness to the host. Separate blessings are required for foods not ordinarily part of the meal, and wine served during the meal may require a blessing unless it was served before the meal or is expected. Grace after the meal should be said without interruption, and washing the fingers after the meal is recommended.
12, GRACE AFTER MEALS (benching) : This chapter provides guidance on the practice of saying grace after a meal. It is desirable to hold a cup of wine while saying grace, and wine is preferable for this purpose. When eating in a group, one person must call on the group to say grace. Grace may be said in any language, and a person may fulfill the obligation by listening to another person saying it and answering "Amen" to each blessing. The rules regarding when and how to say grace, exemptions from saying grace, and other specific scenarios are detailed in this chapter.
"""      

CATEGORIES_2 = """13, BLESSINGS ON FOODS, DRINKS, AND FRAGRANCES : This chapter outlines the rules and guidelines for reciting blessings on food and drinks. A blessing must be recited before consuming even a small quantity of food or drink. The type of blessing to be recited depends on the primary ingredient in the mixture, which is usually the one that gives it its flavor. However, blessings are not recited on foods or drinks that are not normally suitable for consumption, are taken solely for medicinal purposes, or come from forbidden sources. When two or more people are sitting together, one person may recite the blessings before and after bread or wine for all of them, provided they listen with the intent of fulfilling their obligations; however, this must not be done for other foods or drinks. Additionally, there are specific blessings for pleasant fragrances, depending on the source of the fragrance.
14, BLESSINGS ON SPECIFIC FOODS : This chapter explains the blessings recited before and after consuming various types of food and drinks. Bread requires the blessing "...Who brings bread out of the earth," and grace should be said after eating it. Wine and grape-related products have the blessing "...Who creates the fruit of the vine," while other fruits, vegetables, and grains have their specific blessings. The blessing after most foods is "...Who creates many souls..." unless it's a particular type of food with a specific blessing.
15, BLESSINGS ON OTHER OCCASIONS : This chapter discusses the guidelines for reciting blessings in various situations. Every blessing must start with the words "Blessed are You, HA-SHEM, our G-d, King of the universe..." and should be recited audibly if possible. There are specific blessings for various events, such as witnessing miracles, experiencing good or bad news, seeing unusual things, and appreciating nature's wonders. Additionally, a person should be grateful for past events, pray for future outcomes, and strive to perform all activities in the service of G-d.
16, AFTERNOON AND EVENING PRAYERS; CONDUCT AT NIGHT : This chapter covers the guidelines for reciting the afternoon and evening prayers (Shemoneh Esreh) and the evening Shema. The afternoon prayer can be recited starting half an hour after noon or preferably half an hour after midafternoon until sunset or 1-1/4 hours before sunset. The evening prayer can be recited after nightfall until midnight or preferably before dawn. The Shema should be recited just after dark, and Torah study at night is considered essential. The chapter also discusses the proper conduct regarding relations with one's spouse, emphasizing the importance of fulfilling obligations and having intentions for having children rather than personal pleasure.
17, PREPARATIONS FOR THE SABBATH : This chapter provides instructions on preparing for and observing the Sabbath. Before the Sabbath, one should make food, prepare special utensils, and straighten the house. It is customary not to eat large meals on Friday and to avoid regular work or intensive study on Friday afternoon. The Sabbath begins at nightfall, signaled by lighting candles and reciting the blessing. There are guidelines for accepting the Sabbath early, and certain activities are restricted until the Sabbath ends on Saturday night.
18, WORK DONE BY A NON-JEW ON THE SABBATH : This chapter deals with the interactions between Jews and non-Jews on the Sabbath. A Jew should not ask a non-Jew to do work for him on the Sabbath, but he may hire a non-Jew to do work or business as long as the Sabbath is not specified, and the work is not done on the Jew's premises or known to be done for him. Non-Jews may do certain work on the Sabbath if it is only rabbinically forbidden to Jews and is necessary for sickness, great need, or religious purposes. Rules are provided for handling equipment, animals, and goods in relation to non-Jews on the Sabbath.
19, WORK STARTED BEFORE THE SABBATH : The chapter covers various rules and scenarios related to preparing and handling food on the Sabbath, including starting a process before the Sabbath that continues on the day, leaving food on a stove, covering food to keep it warm, and precautions when taking items outside the home near the Sabbath.
20, THE SABBATH PRAYERS : The chapter discusses various customs and procedures related to Sabbath prayers, including modifications in the wording of certain prayers, additional Psalms and readings, and the HAVDALAH prayer added to the evening service at the conclusion of the Sabbath. It also covers rules on reciting prayers on the Sabbath, including restrictions on mourning and praying for personal needs, and the reading of Torah and Prophets portions in the synagogue.
21, KIDDUSH, HAVDALAH, AND THE SABBATH MEALS : The chapter covers various aspects of Sabbath meals and rituals, including the recitation of Kiddush on Friday evening and the blessings on wine, bread, and the Sabbath in the Sabbath morning Kiddush. It emphasizes the importance of bread in Sabbath meals and the need to eat at enjoyable times. It also explains the customs and blessings of the Havdalah ceremony, marking the end of the Sabbath on Saturday night.
22, FIRE AND FOOD PREPARATION ON THE SABBATH : The chapter discusses various prohibitions related to fire, such as adjusting a fire, separating inferior material from food, squeezing juice from fruit, and cooking on the Sabbath. It explains when certain actions are allowed or forbidden, like extinguishing a fire in dangerous situations or allowing some forms of heating of food. The chapter also addresses specific scenarios related to food preparation and handling to ensure compliance with Sabbath regulations.
23, CARE OF THE BODY AND CLOTHING ON THE SABBATH : The chapter discusses various laws related to personal cleanliness and carrying items on the Sabbath. It explains what types of washing are permitted and forbidden, including bathing in hot water or using certain substances. It also covers rules for handling clothing, such as folding, shaking, or wiping them, and what types of items can be worn or carried outside a private domain on the Sabbath. Additionally, the chapter addresses specific scenarios and exceptions, such as medical necessities or carrying items for religious purposes.
24, ANIMALS, CHILDREN, AND THE SICK ON THE SABBATH : This chapter deals with the treatment of animals, medical care on the Sabbath, and care for newborns. It explains that capturing and killing animals are generally forbidden, except in cases of danger. It allows for the alleviation of animal suffering but prohibits other forms of care for sick animals. Regarding medical care on the Sabbath, it permits necessary actions to save a life, while non-life-threatening conditions may have restrictions. For newborns, it discusses circumcision and the importance of teaching them to observe religious laws as they grow older.
"""

CATEGORIES_3 = """25, CONSTRUCTIVE ACTIVITIES ON THE SABBATH : This chapter covers various prohibitions related to creating and altering structures and objects. Making or removing partitions, breaking utensils, fixing or assembling objects, and tying permanent knots are among the forbidden actions. It also prohibits actions related to plants and trees, such as gathering or detaching parts, dropping seeds, and making direct use of trees above a certain height from the ground. Exceptions and specific guidelines are provided for certain situations.
26, OTHER ACTIVITIES ON THE SABBATH : This chapter covers various guidelines related to Sabbath observance in daily activities and interactions. It highlights the permissible and forbidden actions during the Sabbath, such as walking, running for specific purposes, and engaging in enjoyable conversation. It also addresses matters related to reading secular documents, making agreements, conducting business, playing games of chance, and performing certain activities like arresting or judging others, marriage or divorce, and handling vows during the Sabbath.
27, THINGS THAT MUST NOT BE HANDLED ON THE SABBATH (muchtza) : This chapter outlines rules regarding the handling of various objects and utensils on the Sabbath. It specifies which items can be touched, moved, or handled, and under what circumstances. There are guidelines for handling broken utensils, forbidden or repulsive objects, and food that was prepared or existed before the Sabbath. The chapter also addresses the handling of large quantities of food or water and the rescue of food from spilling.
28, MOVING THINGS FROM ONE DOMAIN TO ANOTHER ON THE SABBATH : 
29, RESTRICTIONS ON PRIVATE DOMAINS; COMBINING PRIVATE DOMAINS
30, THE SABBATH BOUNDARY
31, THE CALENDAR AND THE NEW MOON
32, PREPARING FOR PASSOVER; DISPOSING OF CHAMETZ (LEAVEN)
33, OTHER CHAMETZ LAWS
34, MATZAH (UNLEAVENED BREAD)
35, THE PASSOVER SERVICES; THE OMER AND SHAVUOS
36, WORK ON HOLIDAYS
"""

CATEGORIES_4 = """37, SPECIFIC TYPES OF WORK
38, THE INTERMEDIATE DAYS OF THE HOLIDAYS
39, THE FOUR FASTS AND THE NINTH OF AV
40, PRIVATE AND PUBLIC FASTS
41, ROSH HA-SHANAH (THE NEW YEAR)
42, YOM KIPPUR (THE DAY OF ATONEMENT)
43, SUKKOS (TABERNACLES)
44, THE SUKKAH
45, THE FOUR SPECIES
46, CHANUKAH
47, PURIM """

CATEGORIES_LIST = [CATEGORIES_1, CATEGORIES_2, CATEGORIES_3, CATEGORIES_4]
